### ISSUE TITLE
can not import this model

### ISSUE THREAD

**Issue by bhj8** [gsarridis/NSFW-Detection-Pytorch#1]
Thank you for your contribution. But I can't use it normally, I executed it correctly
pip install --upgrade nsfwdetection
And prompt me to install correctly. But I still can't import this library, I can't figure out where the problem is. I can use other commonly used libraries normally.

**Comment by gsarridis** [comment]
Hi, thanks for opening this issue. Try importing the following: from nsfw_detector.model import Model
Let me know if the issue has been solved.
